### PR TITLE
Update to 2.1.0

### PR DESCRIPTION
**Pull request by jnordberg**
Update to latest nunjucks and expose autoescape option.

Also added the correct SPDX license identifier and removed the unnecessary preferGlobal option in package.json. I hope you don't mind :)

### CODE REVIEW

**Comment by jbuck** [comment]
Thanks for doing this patch!

I wonder if it'd be better to do a major semver release (v1.0), and have autoescaping enabled by default. Users would need to specifically opt-in to the new 1.0 version in their package.json, and new users get the security benefits of autoescaping. What do you think?

**Comment by jnordberg** [comment]
Yeah you're right, that's better.

**Comment by jbuck** [comment]
@jnordberg okay great!

**Comment by jbuck** [comment]
@jnordberg Okay, I've published v1.0.0. Thanks for the PR!

**Comment by jnordberg** [comment]
:beers:

**Comment by jbuck** [comment]
:tada:

**Pull request merged**
